# Generated by Django 6.0 on 2026-01-04 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Agendamento')),
                ('algoritmo', models.CharField(choices=[('busca_local', 'Busca Local'), ('simulated_annealing', 'Simulated Annealing')], max_length=50)),
                ('num_maquinas', models.IntegerField(default=3, verbose_name='Número de Máquinas')),
                ('solucao_json', models.JSONField(blank=True, null=True, verbose_name='Solução (JSON)')),
                ('makespan', models.IntegerField(blank=True, null=True, verbose_name='Makespan')),
                ('penalidade_total', models.IntegerField(blank=True, null=True, verbose_name='Penalidade Total')),
                ('tempo_execucao', models.FloatField(blank=True, null=True, verbose_name='Tempo de Execução (s)')),
                ('parametros_json', models.JSONField(default=dict, verbose_name='Parâmetros do Algoritmo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('executado_em', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Agendamento',
                'verbose_name_plural': 'Agendamentos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TarefaProducao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Tarefa')),
                ('duracao', models.IntegerField(help_text='Duração em minutos', verbose_name='Duração')),
                ('prioridade', models.IntegerField(choices=[(1, 'Baixa'), (2, 'Média'), (3, 'Alta')], default=1, verbose_name='Prioridade')),
                ('deadline', models.IntegerField(default=0, help_text='Prazo máximo em minutos', verbose_name='Prazo Máximo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tarefa de Produção',
                'verbose_name_plural': 'Tarefas de Produção',
                'ordering': ['prioridade', 'nome'],
            },
        ),
    ]
